field: 5d22236e-d797-404d-951e-3c732c7547bf # Training program items
fieldLayouts:
  fd301d19-ffd4-4ceb-9dc1-cafdcd0c7efe:
    tabs:
      -
        elements:
          -
            fieldUid: fd8e971a-b625-4d9f-9280-b0a8b9ae9a74 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f0cb5dc5-133b-4644-b13d-280a2c5332d3 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  f0cb5dc5-133b-4644-b13d-280a2c5332d3: # Description
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: mxDescription
    instructions: ''
    name: Description
    searchable: false
    settings:
      errorMessage: 'Unable to find component class ''craft\redactor\Field''.'
      expectedType: craft\redactor\Field
      settings: '{"availableTransforms":"*","availableVolumes":"*","cleanupHtml":true,"columnType":"text","configSelectionMode":"choose","defaultTransform":"","manualConfig":"","purifierConfig":"","purifyHtml":"1","redactorConfig":"","removeEmptyTags":"1","removeInlineStyles":"1","removeNbsp":"1","showHtmlButtonForNonAdmins":"","showUnpermittedFiles":false,"showUnpermittedVolumes":false,"uiMode":"enlarged"}'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
  fd8e971a-b625-4d9f-9280-b0a8b9ae9a74: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: mxTitle
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: skillblock
name: SkillsBlock
sortOrder: 1
