columnSuffix: null
contentColumnType: string
fieldGroup: 5fd5dfe6-4684-4ec8-b94b-0aaae1d9b339 # Home
handle: homeHireItems
instructions: ''
name: 'Home hire items'
searchable: false
settings:
  contentTable: '{{%matrixcontent_homehireitems}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
