columnSuffix: null
contentColumnType: string
fieldGroup: 5fd5dfe6-4684-4ec8-b94b-0aaae1d9b339 # Home
handle: homeProjectsItems1
instructions: null
name: 'Home projects items 1'
searchable: false
settings:
  contentTable: '{{%matrixcontent_homeprojectsitems1}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
