columnSuffix: null
contentColumnType: text
fieldGroup: 5fd5dfe6-4684-4ec8-b94b-0aaae1d9b339 # Home
handle: homeIntroSubtitle
instructions: ''
name: 'Home intro subtitle'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
