columnSuffix: null
contentColumnType: string
fieldGroup: 5fd5dfe6-4684-4ec8-b94b-0aaae1d9b339 # Home
handle: homeSkillsItems
instructions: null
name: 'Home skills items'
searchable: false
settings:
  contentTable: '{{%matrixcontent_homeskillsitems}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
