columnSuffix: null
contentColumnType: text
fieldGroup: b3c111d9-0a13-4069-a080-8f14d635954e # Training
handle: trainingIntroTitle
instructions: ''
name: 'Training intro title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
